name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  PNPM_VERSION: latest-5
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: NODE_OPTIONS=--no-experimental-fetch npm test
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16.14.0
          - 18.0.0
          - 18
          - 19
        include:
          - node: 18
            options: '--no-experimental-fetch'
          - node: 18.0.0
            options: '--no-experimental-fetch'
          - node: 19
            options: '--no-experimental-fetch'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm clean-install
      - run: NODE_OPTIONS="${{ matrix.options }}" npm test
  release:
    needs:
      - verify
      - verify-matrix
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
permissions:
  contents: read
