name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  PNPM_VERSION: latest-5
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
      - uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14.15.0
          - 16.0.0
          - 16
          - 18
          - 19
        include:
          - node: 18
            options: '--no-experimental-fetch'
          - node: 18.0.0
            options: '--no-experimental-fetch'
          - node: 19
            options: '--no-experimental-fetch'
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: NODE_OPTIONS="${{ matrix.options }}" npm test
  release:
    needs:
      - verify
      - verify-matrix
    uses: form8ion/.github/.github/workflows/release-package-semantic-release-19.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
